import { useState } from "react";
import TeacherResource, { Field, SelectField, getApiError } from "../../components/teacher/TeacherResource";
import { generateQuiz } from "../../services/aiService";

const AIQuiz = () => {
  const [form, setForm] = useState({ topic: "", number_of_questions: 10, difficulty: "medium" }); const [result, setResult] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const change = (e) => setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  const submit = async (e) => { e.preventDefault(); try { setLoading(true); setError(""); const response = await generateQuiz({ ...form, number_of_questions: Number(form.number_of_questions) }); setResult(response?.data?.response || response?.response || response?.data || "Quiz generated, but no response text was returned."); } catch (err) { setError(getApiError(err, "Unable to generate quiz.")); } finally { setLoading(false); } };
  return <TeacherResource title="AI Quiz Generator" subtitle="Generate a practice quiz through the Laravel AI service."><div className="grid gap-6 xl:grid-cols-[380px_1fr]"><form onSubmit={submit} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Field label="Topic" name="topic" value={form.topic} onChange={change} placeholder="Machine learning" required /><Field label="Number of questions" type="number" min="1" max="20" name="number_of_questions" value={form.number_of_questions} onChange={change} required /><SelectField label="Difficulty" name="difficulty" value={form.difficulty} onChange={change}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></SelectField>{error && <p className="text-sm text-rose-700">{error}</p>}<button disabled={loading} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{loading ? "Generating..." : "Generate Quiz"}</button></form><section className="min-h-64 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="text-lg font-bold text-slate-800">Generated Quiz</h3>{result ? <pre className="mt-4 whitespace-pre-wrap font-sans text-sm leading-6 text-slate-700">{result}</pre> : <p className="mt-4 text-sm text-slate-500">Your generated quiz will appear here.</p>}</section></div></TeacherResource>;
};
export default AIQuiz;
