import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import TeacherResource, { Field, SelectField, getApiError } from "../../components/teacher/TeacherResource";
import { createAssignment, getAssignment, updateAssignment } from "../../services/assignmentService";
import { getTeacherDashboard } from "../../services/teacherService";

const blank = { course_id: "", title: "", description: "", deadline: "" };
const AssignmentForm = () => {
  const { id } = useParams(); const navigate = useNavigate(); const [courses, setCourses] = useState([]); const [form, setForm] = useState(blank); const [loading, setLoading] = useState(Boolean(id)); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { Promise.all([getTeacherDashboard(), id ? getAssignment(id) : Promise.resolve(null)]).then(([dashboard, assignment]) => { setCourses(dashboard.courses || []); if (assignment) { const item = assignment.data || assignment; setForm({ course_id: item.course_id || "", title: item.title || "", description: item.description || "", deadline: item.deadline ? item.deadline.slice(0, 16) : "" }); } }).catch((e) => setError(getApiError(e, "Unable to load the assignment form."))).finally(() => setLoading(false)); }, [id]);
  const change = (e) => setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  const submit = async (e) => { e.preventDefault(); try { setSaving(true); setError(""); const user = JSON.parse(localStorage.getItem("user") || "null"); const payload = { ...form, teacher_id: user?.id }; if (id) await updateAssignment(id, payload); else await createAssignment(payload); navigate("/teacher/assignments"); } catch (err) { setError(getApiError(err, "Unable to save assignment.")); } finally { setSaving(false); } };
  return <TeacherResource title={id ? "Edit Assignment" : "Create Assignment"} subtitle="Use only courses assigned to you.">{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}{loading ? <p className="text-sm text-slate-500">Loading...</p> : <form onSubmit={submit} className="max-w-2xl space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><SelectField label="Course" name="course_id" value={form.course_id} onChange={change} required><option value="">Select a course</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.course_code} - {course.course_name}</option>)}</SelectField><Field label="Title" name="title" value={form.title} onChange={change} required /><Field label="Deadline" type="datetime-local" name="deadline" value={form.deadline} onChange={change} required /><label className="block text-sm font-medium text-slate-700"><span className="mb-2 block">Description</span><textarea name="description" value={form.description} onChange={change} rows="6" required className="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 outline-none focus:border-blue-500 focus:bg-white" /></label><button disabled={saving} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving..." : id ? "Save Changes" : "Create Assignment"}</button></form>}</TeacherResource>;
};
export default AssignmentForm;
