import { useEffect, useState } from "react";
import { Trash2, Upload } from "lucide-react";
import TeacherResource, { Field, SelectField, getApiError } from "../../components/teacher/TeacherResource";
import { createMaterial, deleteMaterial, getMaterials } from "../../services/materialService";
import { getTeacherDashboard } from "../../services/teacherService";

const CourseMaterials = () => {
  const [items, setItems] = useState([]); const [courses, setCourses] = useState([]); const [form, setForm] = useState({ course_id: "", title: "", file: null }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const load = () => { setLoading(true); Promise.all([getMaterials(), getTeacherDashboard()]).then(([materials, dashboard]) => { setItems(Array.isArray(materials) ? materials : []); setCourses(dashboard.courses || []); }).catch((e) => setError(getApiError(e, "Unable to load course materials."))).finally(() => setLoading(false)); };
  useEffect(load, []);
  const submit = async (e) => { e.preventDefault(); try { setSaving(true); setError(""); const data = new FormData(); data.append("course_id", form.course_id); data.append("title", form.title); data.append("file", form.file); await createMaterial(data); setForm({ course_id: "", title: "", file: null }); setSuccess("Material uploaded successfully."); load(); } catch (err) { setError(getApiError(err, "Unable to upload material.")); } finally { setSaving(false); } };
  const remove = async (id) => { if (!window.confirm("Delete this material?")) return; try { await deleteMaterial(id); load(); } catch (err) { setError(getApiError(err, "Unable to delete material.")); } };
  const change = (e) => setForm((prev) => ({ ...prev, [e.target.name]: e.target.type === "file" ? e.target.files[0] : e.target.value }));
  return <TeacherResource title="Course Materials" subtitle="Upload and manage materials for your assigned courses."><div className="grid gap-6 xl:grid-cols-[1fr_380px]"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <p className="p-6 text-sm text-slate-500">Loading materials...</p> : items.length === 0 ? <p className="p-6 text-sm text-slate-500">No course materials found.</p> : <div className="divide-y divide-slate-100">{items.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 p-5"><div className="min-w-0"><p className="truncate font-semibold text-slate-800">{item.title}</p><p className="text-sm text-slate-500">{item.course?.course_code || item.course_id}</p><p className="truncate text-xs text-slate-400">{item.file_path || "No file path"}</p></div><button type="button" onClick={() => remove(item.id)} className="shrink-0 rounded-lg border border-rose-200 p-2 text-rose-700" aria-label="Delete material"><Trash2 size={15} /></button></div>)}</div>}</div><form onSubmit={submit} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-800">Upload Material</h3><SelectField label="Course" name="course_id" value={form.course_id} onChange={change} required><option value="">Select a course</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.course_code} - {course.course_name}</option>)}</SelectField><Field label="Material title" name="title" value={form.title} onChange={change} required /><Field label="File" type="file" name="file" onChange={change} required />{success && <p className="text-sm text-emerald-700">{success}</p>}{error && <p className="text-sm text-rose-700">{error}</p>}<button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Upload size={16} />{saving ? "Uploading..." : "Upload Material"}</button></form></div></TeacherResource>;
};
export default CourseMaterials;
