import { useEffect, useState } from "react";
import { Edit2, Plus, Trash2 } from "lucide-react";
import TeacherResource, { Field, SelectField, getApiError } from "../../components/teacher/TeacherResource";
import { createCtNotice, deleteCtNotice, getCtNotices, updateCtNotice } from "../../services/ctNoticeService";
import { getTeacherDashboard } from "../../services/teacherService";

const blank = { course_id: "", title: "", exam_date: "", start_time: "", end_time: "" };
const CTNotices = () => {
  const [items, setItems] = useState([]); const [courses, setCourses] = useState([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = () => { setLoading(true); Promise.all([getCtNotices(), getTeacherDashboard()]).then(([notices, dashboard]) => { setItems(Array.isArray(notices) ? notices : []); setCourses(dashboard.courses || []); }).catch((e) => setError(getApiError(e, "Unable to load CT notices."))).finally(() => setLoading(false)); };
  useEffect(load, []);
  const change = (e) => setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  const submit = async (e) => { e.preventDefault(); try { setSaving(true); const user = JSON.parse(localStorage.getItem("user") || "null"); const payload = { ...form, teacher_id: user?.id }; if (editing) await updateCtNotice(editing.id, payload); else await createCtNotice(payload); setEditing(null); setForm(blank); load(); } catch (err) { setError(getApiError(err, "Unable to save CT notice.")); } finally { setSaving(false); } };
  const edit = (item) => { setEditing(item); setForm({ course_id: item.course_id || "", title: item.title || "", exam_date: item.exam_date?.slice(0, 10) || "", start_time: item.start_time?.slice(0, 5) || "", end_time: item.end_time?.slice(0, 5) || "" }); };
  const remove = async (id) => { if (!window.confirm("Delete this CT notice?")) return; try { await deleteCtNotice(id); load(); } catch (err) { setError(getApiError(err, "Unable to delete CT notice.")); } };
  return <TeacherResource title="CT Notices" subtitle="Publish test notices for your assigned courses."><div className="grid gap-6 xl:grid-cols-[1fr_380px]"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{loading ? <p className="p-6 text-sm text-slate-500">Loading notices...</p> : items.length === 0 ? <p className="p-6 text-sm text-slate-500">No CT notices found.</p> : <div className="divide-y divide-slate-100">{items.map((item) => <div key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-800">{item.title}</p><p className="text-sm text-slate-500">{item.course?.course_code || item.course_id} · {item.exam_date || "-"}</p><p className="text-xs text-slate-400">{item.start_time || "-"} - {item.end_time || "-"}</p></div><div className="flex gap-2"><button type="button" onClick={() => edit(item)} className="inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 text-xs"><Edit2 size={14} />Edit</button><button type="button" onClick={() => remove(item.id)} className="inline-flex items-center gap-1 rounded-lg border border-rose-200 px-2.5 py-1.5 text-xs text-rose-700"><Trash2 size={14} />Delete</button></div></div>)}</div>}</div><form onSubmit={submit} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-800">{editing ? "Edit CT Notice" : "Create CT Notice"}</h3><SelectField label="Course" name="course_id" value={form.course_id} onChange={change} required><option value="">Select a course</option>{courses.map((course) => <option key={course.id} value={course.id}>{course.course_code} - {course.course_name}</option>)}</SelectField><Field label="Title" name="title" value={form.title} onChange={change} required /><Field label="Exam date" type="date" name="exam_date" value={form.exam_date} onChange={change} required /><div className="grid grid-cols-2 gap-3"><Field label="Start" type="time" name="start_time" value={form.start_time} onChange={change} required /><Field label="End" type="time" name="end_time" value={form.end_time} onChange={change} required /></div>{error && <p className="text-sm text-rose-700">{error}</p>}<button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Plus size={16} />{saving ? "Saving..." : editing ? "Save Changes" : "Create Notice"}</button></form></div></TeacherResource>;
};
export default CTNotices;
