import { useEffect, useState } from "react";
import TeacherResource, { Field, getApiError } from "../../components/teacher/TeacherResource";
import { getProfile, updatePassword, updateProfile } from "../../services/profileService";

const Profile = () => {
  const [profile, setProfile] = useState(null); const [form, setForm] = useState({ name: "", email: "", phone: "", university_id: "" }); const [password, setPassword] = useState({ current_password: "", new_password: "", new_password_confirmation: "" }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { getProfile().then((data) => { setProfile(data); setForm({ name: data.name || "", email: data.email || "", phone: data.phone || "", university_id: data.university_id || "" }); }).catch((e) => setError(getApiError(e, "Unable to load profile."))).finally(() => setLoading(false)); }, []);
  const change = (setter) => (e) => setter((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  const saveProfile = async (e) => { e.preventDefault(); try { setSaving(true); setError(""); const data = await updateProfile(form); setProfile(data); localStorage.setItem("user", JSON.stringify(data)); setMessage("Profile updated successfully."); } catch (err) { setError(getApiError(err, "Unable to update profile.")); } finally { setSaving(false); } };
  const savePassword = async (e) => { e.preventDefault(); try { setSaving(true); setError(""); await updatePassword(password); setPassword({ current_password: "", new_password: "", new_password_confirmation: "" }); setMessage("Password updated successfully."); } catch (err) { setError(getApiError(err, "Unable to update password.")); } finally { setSaving(false); } };
  return <TeacherResource title="Profile" subtitle="Manage your teacher account information.">{loading ? <p className="text-sm text-slate-500">Loading profile...</p> : <div className="grid max-w-4xl gap-6 lg:grid-cols-2"><form onSubmit={saveProfile} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><p className="text-xl font-bold text-slate-800">{profile?.role || "teacher"}</p><p className="text-sm text-slate-500">Personal information</p></div><Field label="Name" name="name" value={form.name} onChange={change(setForm)} required /><Field label="Email" type="email" name="email" value={form.email} onChange={change(setForm)} required /><Field label="Phone" name="phone" value={form.phone} onChange={change(setForm)} /><Field label="University ID" name="university_id" value={form.university_id} onChange={change(setForm)} /><button disabled={saving} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Save Profile</button></form><form onSubmit={savePassword} className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><h3 className="text-xl font-bold text-slate-800">Change Password</h3><p className="text-sm text-slate-500">Use your current password to continue.</p></div><Field label="Current password" type="password" name="current_password" value={password.current_password} onChange={change(setPassword)} required /><Field label="New password" type="password" name="new_password" value={password.new_password} onChange={change(setPassword)} required /><Field label="Confirm new password" type="password" name="new_password_confirmation" value={password.new_password_confirmation} onChange={change(setPassword)} required /><button disabled={saving} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 disabled:opacity-50">Update Password</button></form></div>}{message && <p className="text-sm text-emerald-700">{message}</p>}{error && <p className="text-sm text-rose-700">{error}</p>}</TeacherResource>;
};
export default Profile;
